sonar.projectKey=aigul-b_middle-python-project-83
sonar.organization=aigul-b
sonar.python.coverage.reportPaths=coverage.xml
sonar.sources=.
sonar.exclusions=**/migrations/**,**/tests.py,**/*_test.py,.venv/**
sonar.tests=.
sonar.test.inclusions=**/tests.py,**/test_*.py
sonar.python.version=3.13